services:
  db:
    image: postgres:15
    container_name: hackaton_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: hackaton_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hackaton_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: hackaton_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hackaton.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - hackaton_net

<<<<<<< HEAD
  ollama:
    image: ollama/ollama:latest
    container_name: hackaton_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - hackaton_net

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: hackaton_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - db
      - ollama
    networks:
      - hackaton_net

volumes:
  pgdata:
  ollama_data:
  n8n_data:
=======
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: hackaton_ollama
  #   restart: unless-stopped
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   networks:
  #     - hackaton_net

  # n8n:
  #   image: docker.n8n.io/n8nio/n8n:latest
  #   container_name: hackaton_n8n
  #   restart: unless-stopped
  #   ports:
  #     - "5678:5678"
  #   environment:
  #     - N8N_HOST=localhost
  #     - N8N_PORT=5678
  #     - N8N_PROTOCOL=http
  #     - NODE_ENV=production
  #     - WEBHOOK_URL=http://localhost:5678/
  #     - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
  #   volumes:
  #     - n8n_data:/home/node/.n8n
  #   depends_on:
  #     - db
  #     - ollama
  #   networks:
  #     - hackaton_net

volumes:
  pgdata:
  # ollama_data:
  # n8n_data:
>>>>>>> devlau

networks:
  hackaton_net:
    driver: bridge